# from selenium import webdriver
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.implicitly_wait(5)
# driver.get('https://practice.automationtesting.in/')
# driver.execute_script("window.scrollBy(0,600)","")
# Selenium = driver.find_element_by_css_selector('.post-160 h3')
# Selenium.click()
# Reviews = driver.find_element_by_css_selector("[href='#tab-reviews']")
# Reviews.click()
# Star_btn = driver.find_element_by_class_name("star-5")
# Star_btn.click()
# Com = driver.find_element_by_id("comment")
# Com.send_keys("Nice book!")
# Name = driver.find_element_by_id("author")
# Name.send_keys("Gas")
# Email = driver.find_element_by_id("email")
# Email.send_keys("guzyak2000@mail.ru")
# Submit = driver.find_element_by_name("submit")
# Submit.click()
# driver.quit()
